const products = [
    { id: 1, name: "Product 1", price: 29.99, image: "image1.jpg", category: "Category A", description: "Description for Product 1", rating: 4.5 },
    { id: 2, name: "Product 2", price: 39.99, image: "image2.jpg", category: "Category B", description: "Description for Product 2", rating: 4.0 },
    { id: 3, name: "Product 3", price: 19.99, image: "image3.jpg", category: "Category A", description: "Description for Product 3", rating: 4.7 },
    { id: 4, name: "Product 4", price: 49.99, image: "image4.jpg", category: "Category C", description: "Description for Product 4", rating: 4.2 },
    { id: 5, name: "Product 5", price: 59.99, image: "image5.jpg", category: "Category B", description: "Description for Product 5", rating: 4.3 },
    { id: 6, name: "Product 6", price: 15.99, image: "image6.jpg", category: "Category A", description: "Description for Product 6", rating: 4.8 },
    { id: 7, name: "Product 7", price: 34.99, image: "image7.jpg", category: "Category A", description: "Description for Product 7", rating: 4.3 },
    { id: 8, name: "Product 8", price: 22.99, image: "image8.jpg", category: "Category B", description: "Description for Product 8", rating: 4.6 },
    { id: 9, name: "Product 9", price: 11.99, image: "image9.jpg", category: "Category C", description: "Description for Product 9", rating: 4.5 },
    { id: 10, name: "Product 10", price: 55.99, image: "image10.jpg", category: "Category A", description: "Description for Product 10", rating: 4.7 },
    { id: 11, name: "Product 11", price: 25.99, image: "image11.jpg", category: "Category A", description: "Description for Product 11", rating: 4.2 },
    { id: 12, name: "Product 12", price: 30.99, image: "image12.jpg", category: "Category B", description: "Description for Product 12", rating: 4.1 },
    { id: 13, name: "Product 13", price: 75.99, image: "image13.jpg", category: "Category C", description: "Description for Product 13", rating: 4.8 },
    { id: 14, name: "Product 14", price: 14.99, image: "image14.jpg", category: "Category B", description: "Description for Product 14", rating: 4.6 },
    { id: 15, name: "Product 15", price: 60.99, image: "image15.jpg", category: "Category C", description: "Description for Product 15", rating: 4.0 },
    { id: 16, name: "Product 16", price: 49.99, image: "image16.jpg", category: "Category A", description: "Description for Product 16", rating: 4.3 },
    { id: 17, name: "Product 17", price: 35.99, image: "image17.jpg", category: "Category B", description: "Description for Product 17", rating: 4.1 },
    { id: 18, name: "Product 18", price: 23.99, image: "image18.jpg", category: "Category A", description: "Description for Product 18", rating: 4.7 },
    { id: 19, name: "Product 19", price: 45.99, image: "image19.jpg", category: "Category C", description: "Description for Product 19", rating: 4.2 },
    { id: 20, name: "Product 20", price: 27.99, image: "image20.jpg", category: "Category B", description: "Description for Product 20", rating: 4.6 },
    { id: 21, name: "Product 21", price: 90.99, image: "image21.jpg", category: "Category C", description: "Description for Product 21", rating: 4.3 },
    { id: 22, name: "Product 22", price: 5.99, image: "image22.jpg", category: "Category A", description: "Description for Product 22", rating: 4.5 },
    { id: 23, name: "Product 23", price: 19.99, image: "image23.jpg", category: "Category B", description: "Description for Product 23", rating: 4.8 },
    { id: 24, name: "Product 24", price: 65.99, image: "image24.jpg", category: "Category C", description: "Description for Product 24", rating: 4.0 },
    { id: 25, name: "Product 25", price: 22.99, image: "image25.jpg", category: "Category A", description: "Description for Product 25", rating: 4.7 },
    { id: 26, name: "Product 26", price: 18.99, image: "image26.jpg", category: "Category A", description: "Description for Product 26", rating: 4.6 },
    { id: 27, name: "Product 27", price: 33.99, image: "image27.jpg", category: "Category B", description: "Description for Product 27", rating: 4.4 },
    { id: 28, name: "Product 28", price: 12.99, image: "image28.jpg", category: "Category C", description: "Description for Product 28", rating: 4.7 },
    { id: 29, name: "Product 29", price: 70.99, image: "image29.jpg", category: "Category A", description: "Description for Product 29", rating: 4.2 },
    { id: 30, name: "Product 30", price: 20.99, image: "image30.jpg", category: "Category B", description: "Description for Product 30", rating: 4.5 },
    { id: 31, name: "Product 31", price: 99.99, image: "image31.jpg", category: "Category C", description: "Description for Product 31", rating: 4.9 }
];

export default products;