name: Sync Products

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout website repo
        uses: actions/checkout@v3

      - name: Clone products repo
        run: |
          git clone https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/obiraofficial1-ocean/obira-products.git

      - name: Clean and copy correctly
        run: |
          rm -rf products
          mkdir products
          mkdir products/bracelets
          mkdir products/necklaces
          mkdir products/catch-clips

          cp -r obira-products/bracelets/* products/bracelets/
          cp -r obira-products/necklaces/* products/necklaces/
          cp -r obira-products/catch-clips/* products/catch-clips/

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Fix product structure" || echo "No changes"
          git push
